# Generated by Django 4.2.4 on 2023-08-04 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="challenge",
            field=models.ManyToManyField(to="Challenge.challenge"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="committee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="portfolio_committee",
                to="Challenge.committee",
            ),
        ),
    ]
