# Generated by Django 4.2.4 on 2023-08-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0002_committee_challenge_portfolio_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="short_description",
            field=models.TextField(null=True),
        ),
    ]
