# Generated by Django 4.2.4 on 2023-08-11 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0003_challenge_short_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="committee",
            name="challenge",
        ),
        migrations.RemoveField(
            model_name="portfolio",
            name="committee",
        ),
    ]
