# Generated by Django 4.2.4 on 2023-09-15 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0004_remove_committee_challenge_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Addon",
        ),
        migrations.CreateModel(
            name="SubPortfolio",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("Challenge.portfolio",),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Challenge.committee",
            ),
        ),
    ]
