# Generated by Django 4.2.4 on 2023-09-15 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0005_delete_addon_subportfolio_portfolio_committee"),
    ]

    operations = [
        migrations.AddField(
            model_name="committee",
            name="challenge",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committee_to_challenge",
                to="Challenge.challenge",
            ),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portfolio_to_committee",
                to="Challenge.committee",
            ),
        ),
    ]
