# Generated by Django 4.2.4 on 2023-09-17 14:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0006_committee_challenge_alter_portfolio_committee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={"ordering": ["-name"]},
        ),
    ]
