# Generated by Django 4.2.4 on 2023-08-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="tema",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
