# Generated by Django 4.2.4 on 2023-08-04 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0002_students_tema"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="tema",
            new_name="team",
        ),
    ]
