# Generated by Django 4.2.4 on 2023-08-04 21:18

from django.db import migrations, models

import Student.models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0003_rename_tema_students_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="csv_file",
            field=models.FileField(
                null=True, upload_to=Student.models.upload_to
            ),
        ),
    ]
