# Generated by Django 4.2.4 on 2023-08-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0004_school_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="contact",
            field=models.CharField(default="1111111111", max_length=25),
        ),
    ]
