# Generated by Django 4.2.4 on 2023-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0005_alter_students_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="personal_info",
            field=models.TextField(null=True),
        ),
    ]
