# Generated by Django 4.2.4 on 2023-08-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0006_students_personal_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="password",
            field=models.CharField(default="password", max_length=100),
        ),
    ]
