# Generated by Django 4.2.4 on 2023-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0007_students_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="contact",
            field=models.CharField(
                blank=True, default="1111111111", max_length=25, null=True
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="name",
            field=models.CharField(default="Test Name", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="students",
            name="standard",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
