# Generated by Django 4.2.4 on 2023-09-17 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Student", "0008_alter_students_contact_alter_students_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="students",
            name="User",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
