# Generated by Django 4.2.4 on 2023-09-17 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0009_students_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="students",
            old_name="User",
            new_name="user",
        ),
    ]
