# Generated by Django 4.2.4 on 2023-08-11 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Challenge", "0004_remove_committee_challenge_and_more"),
        ("Core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactchallengetable",
            name="status",
            field=models.CharField(
                choices=[
                    ("NF", "Not filled"),
                    ("AW", "Awaiting"),
                    ("AL", "Alloted"),
                ],
                default="NF",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="munchallengetable",
            name="status",
            field=models.CharField(
                choices=[
                    ("NF", "Not filled"),
                    ("AW", "Awaiting"),
                    ("AL", "Alloted"),
                ],
                default="NF",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="impactchallengetable",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Challenge.committee",
            ),
        ),
        migrations.AlterField(
            model_name="impactchallengetable",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Challenge.portfolio",
            ),
        ),
        migrations.AlterField(
            model_name="munchallengetable",
            name="committee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Challenge.committee",
            ),
        ),
        migrations.AlterField(
            model_name="munchallengetable",
            name="portfolio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Challenge.portfolio",
            ),
        ),
    ]
