# Generated by Django 4.2.4 on 2023-09-17 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Student", "0009_students_user"),
        ("Core", "0002_impactchallengetable_status_munchallengetable_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="impactchallengetable",
            name="all_tracker",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ic_to_alltracker",
                to="Core.alltracker",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="munchallengetable",
            name="all_tracker",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mun_to_alltracker",
                to="Core.alltracker",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="impactchallengetable",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Student.school",
            ),
        ),
        migrations.AlterField(
            model_name="impactchallengetable",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Student.students",
            ),
        ),
        migrations.AlterField(
            model_name="munchallengetable",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Student.school",
            ),
        ),
        migrations.AlterField(
            model_name="munchallengetable",
            name="student",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Student.students",
            ),
        ),
    ]
