# Generated by Django 4.2.4 on 2023-09-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Core", "0003_impactchallengetable_all_tracker_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impactchallengetable",
            name="all_tracker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ic_to_alltracker",
                to="Core.alltracker",
            ),
        ),
        migrations.AlterField(
            model_name="munchallengetable",
            name="all_tracker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mun_to_alltracker",
                to="Core.alltracker",
            ),
        ),
    ]
